services:
  web:
    build: .
    container_name: revvo
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql  
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: db_revvo_2025
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: revvo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_revvo_2025
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
